### ISSUE TITLE
Error with Lumen 10x

### ISSUE THREAD

**Issue by eu-it-emdotem** [dusterio/lumen-passport#179]
Problem 1
    - dusterio/lumen-passport[0.1.0, ..., 0.1.7] require illuminate/database ~5.3 -> found illuminate/database[v5.3.0, ..., v5.8.36] but the package is fixed to v10.9.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - dusterio/lumen-passport[0.1.8, ..., 0.2.0] require illuminate/database ~5.3|~5.4 -> found illuminate/database[v5.3.0, ..., v5.8.36] but the package is fixed to v10.9.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - dusterio/lumen-passport[0.2.1, ..., 0.2.4] require illuminate/database ~5.3|~5.4|~5.5 -> found illuminate/database[v5.3.0, ..., v5.8.36] but the package is fixed to v10.9.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - dusterio/lumen-passport[0.2.5, ..., 0.2.14] require illuminate/database ~5.3|~5.4|~5.5|~5.6 -> found illuminate/database[v5.3.0, ..., v5.8.36] but the package is fixed to v10.9.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - dusterio/lumen-passport 0.2.15 requires illuminate/database ~5.3|~5.4|~5.5|~5.6|~6.0 -> found illuminate/database[v5.3.0, ..., v5.8.36, v6.0.0, ..., v6.20.44] but the package is fixed to v10.9.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - dusterio/lumen-passport[0.2.16, ..., 0.2.19] require illuminate/database ~5.3|~5.4|~5.5|~5.6|^6.0|^7.0 -> found illuminate/database[v5.3.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6] but the package is fixed to v10.9.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - dusterio/lumen-passport[0.2.20, ..., 0.3.4] require illuminate/database ~5.3|~5.4|~5.5|~5.6|^6.0|^7.0|^8.0 -> found illuminate/database[v5.3.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but the package is fixed to v10.9.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - dusterio/lumen-passport[0.3.5, ..., 0.3.6] require illuminate/database ~5.3|~5.4|~5.5|~5.6|^6.0|^7.0|^8.0|^9.0 -> found illuminate/database[v5.3.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.7] but the package is fixed to v10.9.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires dusterio/lumen-passport * -> satisfiable by dusterio/lumen-passport[0.1.0, ..., 0.3.6].

**Comment by kumardurairaj** [comment]
Did this package will support for Lumen 10, I am also getting the same error.

**Comment by eu-it-emdotem** [comment]
> Did this package will support for Lumen 10, I am also getting the same error. Please suggest, your response is appreciated.

I think that project it's dead.

Last commit - May 27, 2022

**Comment by Rasoul-Karimi** [comment]
@lloricode
@sanplomb
@benwilkins
@MattApril
@chris-doehring
@santilorenzo
@jmarcher
@beeards
@andrew-s
@majidmvulle

**Comment by jmarcher** [comment]
> plase update composer file to support lumen 10
> 
> @lloricode @sanplomb @benwilkins @MattApril @chris-doehring @santilorenzo @jmarcher @beeards @andrew-s @majidmvulle

What do I have to do with this issue?

**Comment by jmarcher** [comment]
Do you realize I am not the owner of this repo? This is an open source repo you could either do it yourself or fork it and use a for of it for your own projects.

**Comment by Rasoul-Karimi** [comment]
yes i know but you are Contributor ! please supprt it 

now i send pull request you can merge it!?

**Comment by dusterio** [comment]
Sorry guys didn't get any notifications from GitHub - I just merged the PR, this should be fixed now?

**Comment by kumardurairaj** [comment]
Thanks a lot @dusterio  for your support and contribution in upgrading the package, It helps us a lot, keep up your good work 👍

**Comment by Rasoul-Karimi** [comment]
now need to update for support lumen 10 @kumardurairaj

look to file `LumenPassport.php`

![image](https://github.com/dusterio/lumen-passport/assets/9654616/67f29d98-cbfc-4763-8d8d-41b4a89d23e7)

not support lumen 10 !!

@dusterio

**Comment by Rasoul-Karimi** [comment]
> Sorry guys didn't get any notifications from GitHub - I just merged the PR, this should be fixed now?

first please fix your GitHub notification, please!! please

not fixed! look to this file : LumenPassport.php like 67 ! not support lumen 10 i think

**Comment by dusterio** [comment]
@Rasoul-Karimi can you try again please?

**Comment by kumardurairaj** [comment]
Hi @Rasoul-Karimi ,
       I upgraded my composer for lumen 10 with below packages :
       "laravel/lumen-framework": "^10.0",
       "dusterio/lumen-passport": "^0.3.5",
       
       it ran without any issues and it got upgraded.
       **Laravel Framework Lumen (10.0.0) (Laravel Components ^10.0)**
       
       
<img width="614" alt="image" src="https://github.com/dusterio/lumen-passport/assets/48903969/2b885d4f-fa43-480c-8032-6eb0a73d18dc">

       
       Did you still facing issues ? please post here!

**Comment by Rasoul-Karimi** [comment]
> Hi @Rasoul-Karimi , I upgraded my composer for lumen 10 with below packages : "laravel/lumen-framework": "^10.0", "dusterio/lumen-passport": "^0.3.5",
> 
> ```
>    it ran without any issues and it got upgraded.
>    **Laravel Framework Lumen (10.0.0) (Laravel Components ^10.0)**
> ```
> 
> <img alt="image" width="614" src="https://user-images.githubusercontent.com/48903969/259921139-2b885d4f-fa43-480c-8032-6eb0a73d18dc.png">
> ```
>    Did you still facing issues ? please post here!
> ```


Omg only install!!! if you can use and test it! we dont tallk aboute install!

![image](https://github.com/dusterio/lumen-passport/assets/9654616/6b28f8f7-e4f8-4581-a282-64f2c8ecc4a8)

after install use this command and see that error:

`php artisan cache:clear  `

**Comment by Rasoul-Karimi** [comment]
> @Rasoul-Karimi can you try again please?

I test it, and everything is good! successful :)

**Comment by kumardurairaj** [comment]
Good to hear @Rasoul-Karimi  👍
